<svelte:head>
    <title>eat locals!</title>
</svelte:head>

<script>
	import { onMount } from 'svelte';
	import Mapsplaining from '../components/Mapsplaining.svelte';
	import SlippyMap from '../components/SlippyMap.svelte';
	import Mapfilters from '../components/Mapfilters.svelte';
    import Place from '../modules/places.mjs'

	// Component references
    let slippyMap;
	let mapsplainer;

	// Client state
	let highlightedPlace = null;
	let lastPinnedPlace = null;
	let pinnedPlaces = new Set();

    function unpinAllPlaces() {
        pinnedPlaces.forEach(place => { place.unpin(); });
    }

    // Note: the nulls here are placeID, which is our internal ID, but
    // which is currently being randomly generated by the place itself
    let places = [
        new Place(
            'Drexl', null, -122.2674272, 37.8072493, {
                osmID: 3056134586,
                hasFood: false,
                hasBooze: true,
                hasBeer: true,
                hasProvisions: false
        }),
        new Place(
            '355', null, -122.2669739, 37.8068275, {
                osmID: 1079401457,
                hasFood: false,
                hasBooze: true,
                hasBeer: true,
                hasProvisions: false
        }),
        new Place(
            'Itani Ramen', null, -122.2699126, 37.8076042, {
                osmID: 4095991379,
                hasFood: true,
                hasBooze: false,
                hasBeer: true,
                hasProvisions: false
        }),
        new Place(
            'The Telegraph', null, -122.2685736, 37.8128233, {
                osmID: 3470332401,
                hasFood: true,
                hasBooze: true,
                hasBeer: true,
                hasProvisions: false
        }),
        new Place(
            'Duende', null, -122.2695932, 37.8081307, {
                osmID: 3470332399,
                hasFood: true,
                hasBooze: true,
                hasBeer: true,
                hasProvisions: false
        }),
        new Place(
            'The Lunch Box', null, -122.2680771, 37.8065924, {
                osmID: 1186413873,
                hasFood: true,
                hasBooze: false,
                // Note: I don't actually know this for sure; I've never been
                // there
                hasBeer: false,
                hasProvisions: false
        }),
        new Place(
            'Howden Market', null, -122.2672438, 37.8055483, {
                osmID: 3927998690,
                hasFood: true,
                hasBooze: false,
                hasBeer: true,
                hasProvisions: true
        })
    ];

    onMount(() => {
        // TODO: have that place class call into child component instead of
        //       passing events up the chain
        places.forEach(place => {
            place.mountPlace(slippyMap, mapsplainer, pinnedPlaces);
        });
    });
    
    
</script>

<div class="slippymap-container">
	<SlippyMap
	bind:this={slippyMap}/>
</div>
	<div class="slippymap-overlay-container">
	<div class="mapsplaining-container">
		<Mapsplaining
		bind:this={mapsplainer}
        unpinAll={unpinAllPlaces}/>
	</div>
	<div class="mapfilters-container">
		<Mapfilters/>
	</div>
</div>

<style>

	.slippymap-overlay-container {
		box-sizing: border-box;
        pointer-events: none;
		position: absolute;
		left: 0;
		top: 0;
		z-index: 7777;
        height: 100%;
        width: 100%;
		padding: 10px;
	}

	.mapsplaining-container {
		vertical-align: top;
		position: relative;
		display: inline-block;
		margin: 50px;
	}

	.mapfilters-container {
		vertical-align: top;
		position: relative;
		display: inline-block;
		margin: 50px;
	}

	.slippymap-container {
		position: relative;
		width: 100%;
		height: 100%;
	}

	:global(main) {
		color: rgb(254, 245, 247);
		position: relative;
		width: 100%;
		height: 100%;
		margin: 0;
		padding: 0;
	}

	@media (min-width: 640px) {
		:global(main) {
			max-width: none;
		}
	}
</style>
